### ISSUE TITLE
something is wrong with salloc 

### ISSUE THREAD

**Issue by qianglise** [ENCCS/HPDA-Python#54]
when i tried 
salloc -N 1 --ntasks-per-node=8 
and once I launch dask, what  I got is the following
<Client: 'tcp://127.0.0.1:41107' processes=4 threads=8, memory=251.69 GiB>
so --ntasks-per-node=8 allocated 8 threads, 4 cores, rather than 8 cores

or I misunderstood something here

**Comment by wikfeldt** [comment]
i just now noticed the same thing with ipyparallel! So there's a different SLURM flag we should use

**Comment by wikfeldt** [comment]
probably just need to add `--ntasks-per-core=1`

**Comment by wikfeldt** [comment]
fixed in setup instructions in 52fddd89a3efc9339799937dbf3d5fb0d743365c
